"""Boot mode: harness-launched services, any language (T6, plan decision 42).

Managed mode gets per-test environment control by importing the FastAPI app and
driving it in-process, so a probe's ``monkeypatch.setenv`` is visible to the app
immediately. That mechanism is Python-only, which is why the 21 ``sec_managed``
probes auto-skip in attached mode and a TypeScript port could go green having
never exercised agent subprocess hardening, credential isolation, prompt-envelope
containment, token fail-closed defaults, the CORS non-vacuity check, or URL
safety under controlled config.

Boot mode restores that control across a process boundary. The harness *launches*
the service from a command it owns::

    SEC_BOOT_BACKEND_CMD="node dist/server.js --port {port}"
    SEC_BOOT_AI_CMD="python -m uvicorn services.ai_engine.app.main:app --port {port}"

and restarts it whenever the probe mutates the environment, so the child always
serves a request under the environment the probe staged.

Three properties this module exists to guarantee, each of which is a way boot
mode could otherwise report green while observing nothing:

1. **Restart granularity is per REQUEST, not per test.** SEC-22 runs
   ``hatch_absent`` and ``hatch_set`` inside one test function, mutating the
   environment between them and asserting different responses. A per-test
   restart would serve both halves from one process and collapse the probe.
2. **A failed launch RAISES, it never skips.** The managed-mode "app
   unavailable -> skip" path removes probes silently; a crashed child (bad
   command, missing dependency, port collision) taking that path would delete
   exactly the coverage boot mode exists to add. ``BootFailure`` carries the
   child's captured output.
3. **A restart resets service state.** This is inherent to a process boundary:
   the environment is what the process was started with. Probes that stage
   environment, then switch provider, then act are safe because no mutation
   happens between the switch and the act; a probe that needs server state to
   survive an environment change cannot be expressed in boot mode and must say
   so rather than silently observe a fresh process.
"""

from __future__ import annotations

import contextlib
import os
import shlex
import socket
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Optional

BOOT_ENVS = {
    "backend": "SEC_BOOT_BACKEND_CMD",
    "ai": "SEC_BOOT_AI_CMD",
    "browser": "SEC_BOOT_BROWSER_CMD",
}

# Keys pytest and the shell rewrite on their own cadence. Comparing them would
# force a restart before every request, which is merely slow -- but leaving a
# genuinely load-bearing key out of the comparison is a silent false pass, so
# this list stays as short as it can be and every entry is justified.
ENV_NOISE_KEYS = frozenset(
    {
        "PYTEST_CURRENT_TEST",  # rewritten by pytest per test PHASE (setup/call)
        "_",  # last argument of the previous shell command
    }
)

BOOT_TIMEOUT = float(os.getenv("SEC_BOOT_TIMEOUT", "30"))


class BootFailure(RuntimeError):
    """A harness-launched service failed to start or died while serving.

    Deliberately NOT a ``pytest.skip``: an unbootable child means the probes
    that need it did not run, and the suite must say so loudly.
    """


def boot_command(service: str) -> Optional[str]:
    return os.getenv(BOOT_ENVS[service]) or None


def any_boot_configured() -> bool:
    return any(boot_command(service) for service in BOOT_ENVS)


def env_fingerprint() -> dict:
    """The environment a child would be started with, minus known noise."""
    return {k: v for k, v in os.environ.items() if k not in ENV_NOISE_KEYS}


def _free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


# ---------------------------------------------------------------------------
# Playwright shim across the process boundary
# ---------------------------------------------------------------------------

# Managed mode installs a fake ``playwright.async_api`` into ``sys.modules``
# before importing browser-engine, so validation-only probes run without the
# real dependency. ``sys.modules`` does not survive a fork/exec, so boot mode
# reinstalls the SAME shim inside the child via ``sitecustomize``, which CPython
# imports before any application code. Without this, a booted browser-engine
# would fail to import and boot mode would report a launch failure for a reason
# that has nothing to do with the invariant under test.
_SITECUSTOMIZE = '''"""Generated by tests/security/boot.py -- do not edit."""
import sys, types


class _FakeTimeout(Exception):
    pass


def _unavailable(*_args, **_kwargs):
    raise RuntimeError("playwright unavailable in hermetic security harness")


try:
    import playwright.async_api  # noqa: F401
except Exception:
    async_api = types.ModuleType("playwright.async_api")
    async_api.Browser = type("Browser", (), {})
    async_api.Page = type("Page", (), {})
    async_api.TimeoutError = _FakeTimeout
    async_api.async_playwright = _unavailable

    root = types.ModuleType("playwright")
    root.async_api = async_api
    sys.modules.setdefault("playwright", root)
    sys.modules["playwright.async_api"] = async_api
'''


def _shim_dir() -> str:
    """A directory holding ``sitecustomize.py``, created once per session."""
    global _SHIM_DIR
    if _SHIM_DIR is None:
        _SHIM_DIR = tempfile.mkdtemp(prefix="sec-boot-shim-")
        Path(_SHIM_DIR, "sitecustomize.py").write_text(_SITECUSTOMIZE, encoding="utf-8")
    return _SHIM_DIR


_SHIM_DIR: Optional[str] = None


class BootedService:
    """One harness-launched service, restarted whenever its environment drifts.

    The log file is append-only across restarts so a capture window that spans
    one keeps monotonic byte offsets. That matters for SEC-27, which reads the
    service's diagnostics for a planted secret: a rotated file would make the
    window read empty, and "the secret is absent from an empty log" is the
    vacuous pass this whole module is built to prevent.
    """

    def __init__(self, service: str, command: str, workdir: Path):
        self.service = service
        self.command = command
        self.workdir = workdir
        workdir.mkdir(parents=True, exist_ok=True)
        self.log_path = workdir / f"{service}.log"
        self.log_path.touch()
        self._log_handle = self.log_path.open("ab")
        self.proc: Optional[subprocess.Popen] = None
        self.port: Optional[int] = None
        self._booted_env: Optional[dict] = None
        self.boot_count = 0

    # -- lifecycle ---------------------------------------------------------

    @property
    def base_url(self) -> str:
        if self.port is None:
            raise BootFailure(f"{self.service}: asked for a URL before booting")
        return f"http://127.0.0.1:{self.port}"

    def ensure(self, env: dict) -> None:
        """Start the child, or restart it if the staged environment changed."""
        if self.proc is not None and self.proc.poll() is not None:
            raise BootFailure(
                f"{self.service}: child exited with code {self.proc.returncode} "
                f"while serving.\n{self._tail()}"
            )
        if self.proc is None or env != self._booted_env:
            self._restart(env)

    def _restart(self, env: dict) -> None:
        self.stop()
        self.port = _free_port()
        argv = [part.format(port=self.port, host="127.0.0.1") for part in shlex.split(self.command)]

        child_env = dict(env)
        # Reinstall the playwright shim and keep the repo importable, without
        # letting either overwrite what the probe staged.
        existing_path = child_env.get("PYTHONPATH", "")
        parts = [_shim_dir()] + ([existing_path] if existing_path else [])
        child_env["PYTHONPATH"] = os.pathsep.join(parts)
        child_env.setdefault("PYTHONUNBUFFERED", "1")
        # For services that take their port from the environment rather than
        # argv. `{port}` in the command still works; this just spares a
        # `sh -c` wrapper for the common case.
        child_env["SEC_BOOT_PORT"] = str(self.port)

        self._log_handle.write(
            f"\n=== boot #{self.boot_count + 1} {self.service} "
            f"port={self.port} argv={argv!r} ===\n".encode()
        )
        self._log_handle.flush()

        try:
            self.proc = subprocess.Popen(
                argv,
                env=child_env,
                stdout=self._log_handle,
                stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                cwd=str(_repo_root()),
            )
        except OSError as exc:
            raise BootFailure(
                f"{self.service}: could not launch {argv!r}: {exc}"
            ) from exc

        self.boot_count += 1
        self._booted_env = dict(env)
        self._wait_healthy()

    def _wait_healthy(self) -> None:
        """Poll ``/health`` until it answers, or the child dies, or we time out.

        ``/health`` is the right probe because SEC-23 freezes it as tokenless:
        it answers in every environment a probe can stage, including the ones
        SEC-21 builds by deleting the token configuration entirely.
        """
        assert self.proc is not None
        deadline = time.monotonic() + BOOT_TIMEOUT
        last_error = "no connection attempt completed"
        while time.monotonic() < deadline:
            if self.proc.poll() is not None:
                raise BootFailure(
                    f"{self.service}: child exited with code {self.proc.returncode} "
                    f"before serving /health.\n{self._tail()}"
                )
            try:
                with socket.create_connection(("127.0.0.1", self.port), timeout=0.5):
                    pass
            except OSError as exc:
                last_error = str(exc)
                time.sleep(0.05)
                continue
            # The port is open; confirm it is actually this service answering.
            try:
                import httpx

                response = httpx.get(f"{self.base_url}/health", timeout=5.0)
            except Exception as exc:  # still binding, not yet routing
                last_error = str(exc)
                time.sleep(0.05)
                continue
            if response.status_code in (200, 503):
                return
            last_error = f"/health returned {response.status_code}"
            time.sleep(0.05)
        self.stop()
        raise BootFailure(
            f"{self.service}: did not become healthy within {BOOT_TIMEOUT}s "
            f"({last_error}).\n{self._tail()}"
        )

    def stop(self) -> None:
        if self.proc is None:
            return
        with contextlib.suppress(Exception):
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill()
                self.proc.wait(timeout=5)
        self.proc = None
        self._booted_env = None

    def close(self) -> None:
        self.stop()
        with contextlib.suppress(Exception):
            self._log_handle.close()

    # -- diagnostics channel ----------------------------------------------

    def log_size(self) -> int:
        with contextlib.suppress(OSError):
            return self.log_path.stat().st_size
        return 0

    def log_text(self, since: int = 0) -> str:
        """Everything the child wrote to stdout/stderr after byte ``since``."""
        with contextlib.suppress(OSError):
            self._log_handle.flush()
        with contextlib.suppress(OSError):
            with self.log_path.open("rb") as handle:
                handle.seek(since)
                return handle.read().decode("utf-8", "replace")
        return ""

    def _tail(self, limit: int = 4000) -> str:
        text = self.log_text()
        if len(text) > limit:
            text = "...\n" + text[-limit:]
        return f"--- {self.service} output ---\n{text}"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]
