version: '3.8'

services:
  web-ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web-ui-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - scraping_network

networks:
  scraping_network:
    external: true