services:
  # Test Qdrant instance
  test-qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: test-qdrant-chatbot
    ports:
      - "6334:6333"
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    tmpfs:
      - /qdrant/storage
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Test Ollama instance
  test-ollama:
    image: ollama/ollama:latest
    container_name: test-ollama-chatbot
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    tmpfs:
      - /root/.ollama
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Chatbot service under test
  chatbot-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-test
    ports:
      - "8093:8092"
    environment:
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=test
      - QDRANT_HOST=test-qdrant
      - QDRANT_PORT=6333
      - OLLAMA_BASE_URL=http://test-ollama:11434
      - DEFAULT_LLM_MODEL=phi4:3.8b
      - DEFAULT_EMBEDDING_MODEL=mxbai-embed-large
    depends_on:
      test-qdrant:
        condition: service_healthy
      test-ollama:
        condition: service_healthy
    networks:
      - test-network
    volumes:
      - ./test_logs:/app/logs
    command: ["python", "-m", "pytest", "test_chatbot.py", "-v", "--tb=short"]

  # Test runner with coverage (mocked dependencies)
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: chatbot-test-runner
    environment:
      - QDRANT_HOST=test-qdrant
      - QDRANT_PORT=6333
      - OLLAMA_BASE_URL=http://test-ollama:11434
      - PYTHONPATH=/app
      - TEST_MODE=true
    networks:
      - test-network
    volumes:
      - .:/app
      - ./coverage:/app/coverage
    working_dir: /app
    command: |
      sh -c "
        echo '🤖 Running Chatbot Service Tests in Container'
        echo '================================================'
        python -m pytest test_chatbot.py -v --tb=short --cov=main --cov-report=term-missing --cov-report=html:coverage/html --cov-report=xml:coverage/coverage.xml --junit-xml=coverage/junit.xml
        echo '✅ Chatbot tests completed'
      "

  # Integration test runner (with real dependencies)
  integration-test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: chatbot-integration-test-runner
    environment:
      - QDRANT_HOST=test-qdrant
      - QDRANT_PORT=6333
      - OLLAMA_BASE_URL=http://test-ollama:11434
      - PYTHONPATH=/app
    depends_on:
      test-qdrant:
        condition: service_healthy
      test-ollama:
        condition: service_healthy
    networks:
      - test-network
    volumes:
      - .:/app
      - ./coverage:/app/coverage
    working_dir: /app
    command: |
      sh -c "
        echo '🤖 Running Chatbot Integration Tests in Container'
        echo '================================================='
        python -m pytest test_chatbot.py::test_integration_flow -v --tb=short
        echo '✅ Integration tests completed'
      "

networks:
  test-network:
    driver: bridge

volumes:
  test_logs:
    driver: local